name: CI-Release

on: [ push, pull_request ]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker Layer Caching
        uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true
        with:
          key: quicksdl-docker-cache-{hash}
          restore-keys: |
            quicksdl-docker-cache-
      - name: Build artifacts
        run: |
          docker build . --file Dockerfile --tag builder
          docker run --rm -v ${PWD}:/project builder make -j$(nproc)
      - name: Upload RPX
        uses: actions/upload-artifact@v3
        with:
          name: ExampleGame.rpx
          path: ExampleGame.rpx
          if-no-files-found: warn